# Generated by Django 6.0.3 on 2026-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, help_text="25", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="antecedents_medicaux",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_dernieres_regles",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_prevue_accouchement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="groupe_sanguin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nombre_grossesses_precedentes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="poids_initial",
            field=models.FloatField(help_text="En kg", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="taille",
            field=models.PositiveIntegerField(blank=True, help_text="En cm", null=True),
        ),
    ]
