# Generated by Django 6.0.3 on 2026-04-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_user_age_user_antecedents_medicaux_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_dernieres_regles",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="poids_initial",
            field=models.FloatField(blank=True, help_text="En kg", null=True),
        ),
    ]
