# Generated by Django 6.0.3 on 2026-04-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_chatmessage_id_alter_notification_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_analyse", models.DateTimeField(auto_now_add=True)),
                ("analyse_textuelle", models.TextField()),
                ("score_vigilance", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_ia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_analyse"],
            },
        ),
    ]
