# Generated by Django 6.0.3 on 2026-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_rapportia"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportia",
            name="conseils",
            field=models.JSONField(default=list),
        ),
    ]
