# Generated by Django 6.0.3 on 2026-04-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0008_rapportia_conseils"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RapportIA",
        ),
    ]
