# Generated by Django 6.0.3 on 2026-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_delete_rapportia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nombre_grossesses_precedentes",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
