# Generated by Django 6.0.3 on 2026-04-09 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloppementFoetus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine", models.PositiveIntegerField(unique=True)),
                ("poids_moyen", models.FloatField(help_text="en grammes")),
                ("taille_moyenne", models.FloatField(help_text="en cm")),
                ("stade_developpement", models.TextField()),
                ("note_importante", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuiviHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine_grossesse", models.PositiveIntegerField()),
                ("poids", models.FloatField(help_text="Poids en kg")),
                (
                    "tension_systolique",
                    models.IntegerField(help_text="ex: 12 pour 12/8", null=True),
                ),
                (
                    "tension_diastolique",
                    models.IntegerField(help_text="ex: 8 pour 12/8", null=True),
                ),
                (
                    "temperature",
                    models.FloatField(help_text="Température en °C", null=True),
                ),
                (
                    "niveau_fatigue",
                    models.IntegerField(
                        help_text="1 (faible) à 5 (très élevé)", null=True
                    ),
                ),
                (
                    "niveau_stress",
                    models.IntegerField(
                        help_text="1 (faible) à 5 (très élevé)", null=True
                    ),
                ),
                (
                    "qualite_sommeil",
                    models.IntegerField(
                        help_text="1 (faible) à 5 (très élevé)", null=True
                    ),
                ),
                ("douleur", models.BooleanField(default=False, null=True)),
                ("nausees", models.BooleanField(default=False, null=True)),
                ("vomissements", models.BooleanField(default=False, null=True)),
                ("saignement", models.BooleanField(default=False, null=True)),
                ("mouvement_bebe", models.BooleanField(default=True, null=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("eleve", "Élevé"),
                        ],
                        default="faible",
                        max_length=10,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivis_grossesse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlerteMedicale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("niveau_risque", models.CharField(max_length=10)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "mere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suivi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pregancy.suivihebdomadaire",
                    ),
                ),
            ],
        ),
    ]
