# Generated by Django 6.0.3 on 2026-04-09 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertemedicale",
            options={"ordering": ["-date_creation"]},
        ),
        migrations.AlterModelOptions(
            name="suivihebdomadaire",
            options={"ordering": ["-date_creation"]},
        ),
        migrations.AddField(
            model_name="alertemedicale",
            name="lu",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="douleur",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="mouvement_bebe",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="nausees",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="niveau_fatigue",
            field=models.IntegerField(
                blank=True, help_text="1 (faible) à 5 (très élevé)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="niveau_stress",
            field=models.IntegerField(
                blank=True, help_text="1 (faible) à 5 (très élevé)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="qualite_sommeil",
            field=models.IntegerField(
                blank=True, help_text="1 (faible) à 5 (très élevé)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="saignement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="temperature",
            field=models.FloatField(
                blank=True, help_text="Température en °C", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="tension_diastolique",
            field=models.IntegerField(
                blank=True, help_text="ex: 8 pour 12/8", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="tension_systolique",
            field=models.IntegerField(
                blank=True, help_text="ex: 12 pour 12/8", null=True
            ),
        ),
        migrations.AlterField(
            model_name="suivihebdomadaire",
            name="vomissements",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="suivihebdomadaire",
            unique_together={("mere", "semaine_grossesse")},
        ),
    ]
